hostname IR1

ipv6 unicast-routing
ipv6 router ospf 10
 router-id 3.3.3.3
 passive-interface g0/0.11
 passive-interface g0/0.22
 passive-interface g0/0.33
 passive-interface g0/0.60
 passive-interface g0/0.88

interface s0/0/0 
 ipv6 ospf 10 a 0 

interface GigabitEthernet0/0
 no shutdown

interface GigabitEthernet0/0.11
 encapsulation dot1Q 11
 ipv6 ospf 10 a 0 

interface GigabitEthernet0/0.22
 encapsulation dot1Q 22

interface GigabitEthernet0/0.33
 encapsulation dot1Q 33

interface GigabitEthernet0/0.60
 encapsulation dot1Q 60

interface GigabitEthernet0/0.88
 encapsulation dot1Q 88

router ospf 10 
 router- 3.3.3.3
 passive-interface g0/0.11
 passive-interface g0/0.22
 passive-interface g0/0.33
 passive-interface g0/0.60
 passive-interface g0/0.88
 network 192.168.11.0 0.0.0.255 a 0
 network 192.168.22.0 0.0.0.255 a 0
 network 192.168.33.0 0.0.0.255 a 0
 network 192.168.60.0 0.0.0.255 a 0
 network 192.168.88.0 0.0.0.255 a 0