hostname IS1


vlan 11
 name HR
vlan 22
 name SALES
vlan 33
 name MARKETING
vlan 60
 name WLAN
vlan 88
 name MANAGEMENT
vlan 99
 name BLACKHOLE


no cdp run
no lldp run
spanning-tree mode rapid-pvst
spanning-tree portfast bpduguard default
spanning-tree portfast bpdufilter default

no service tcp-small-servers
no service udp-small-servers
no ip http server
no ip http secure-server


interface FastEthernet0/1
 description ACCESS_HR_VLAN11
 switchport mode access
 switchport access vlan 11
 switchport nonegotiate
 spanning-tree portfast
 spanning-tree bpduguard enable
 switchport port-security
 switchport port-security maximum 1
 switchport port-security mac-address sticky
 switchport port-security violation shutdown
 ip dhcp snooping limit rate 15
 ip arp inspection limit rate 100
 no cdp enable
 no lldp transmit
 no lldp receive
 no shutdown

interface FastEthernet0/2
 description ACCESS_SALES_VLAN22
 switchport mode access
 switchport access vlan 22
 switchport nonegotiate
 spanning-tree portfast
 spanning-tree bpduguard enable
 switchport port-security
 switchport port-security maximum 1
 switchport port-security mac-address sticky
 switchport port-security violation shutdown
 ip dhcp snooping limit rate 15
 ip arp inspection limit rate 100
 no cdp enable
 no lldp transmit
 no lldp receive
 no shutdown

interface FastEthernet0/3
 description ACCESS_MARKETING_VLAN33
 switchport mode access
 switchport access vlan 33
 switchport nonegotiate
 spanning-tree portfast
 spanning-tree bpduguard enable
 switchport port-security
 switchport port-security maximum 1
 switchport port-security mac-address sticky
 switchport port-security violation shutdown
 ip dhcp snooping limit rate 15
 ip arp inspection limit rate 100
 no cdp enable
 no lldp transmit
 no lldp receive
 no shutdown

interface GigabitEthernet0/1
 description ACCESS_WLAN_VLAN60
 switchport mode access
 switchport access vlan 60
 switchport nonegotiate
 spanning-tree portfast
 spanning-tree bpduguard enable
 switchport port-security
 switchport port-security maximum 50
 switchport port-security mac-address sticky
 switchport port-security violation restrict
 ip dhcp snooping limit rate 30
 ip arp inspection limit rate 200
 no cdp enable
 no lldp transmit
 no lldp receive
 no shutdown


interface GigabitEthernet0/2
 description UPLINK_TRUNK
 switchport mode trunk
 switchport trunk allowed vlan 11,22,33,60,88
 switchport trunk native vlan 99
 switchport nonegotiate
 spanning-tree guard root
 no cdp enable
 no lldp transmit
 no lldp receive
 no shutdown


interface Vlan88
 description MANAGEMENT
 ip address 192.168.88.9 255.255.255.0
 no shutdown


interface range FastEthernet0/4 - 24
 description UNUSED_DISABLED
 switchport mode access
 switchport access vlan 99
 switchport nonegotiate
 spanning-tree portfast
 spanning-tree bpduguard enable
 no cdp enable
 no lldp transmit
 no lldp receive
 shutdown


ip dhcp snooping
ip dhcp snooping vlan 11,22,33,60,88
no ip dhcp snooping information option


ip arp inspection vlan 11,22,33,60,88


ip default-gateway 192.168.88.6

ip access-list standard MGMT_ACCESS
 permit 192.168.88.0 0.0.0.255
 deny   any log

line vty 0 15
 access-class MGMT_ACCESS in
 transport input ssh
 exec-timeout 5 0
 login local

line console 0
 exec-timeout 5 0
 login local
