hostname IS1

vlan 11
 name HR
vlan 22
 name SALES
vlan 33
 name MARKETING
vlan 60
 name WLAN
vlan 88
 name MANAGEMENT
vlan 
 name BLACKHOLE

interface FastEthernet0/1
 switchport mode access
 switchport access vlan 11

interface FastEthernet0/2
 switchport mode access
 switchport access vlan 22

interface FastEthernet0/3
 switchport mode access
 switchport access vlan 33

interface GigabitEthernet0/0
 switchport mode access
 switchport access vlan 60

interface GigabitEthernet0/2
 switchport mode trunk
 sw tr all vl 11,22,33,60,88 
 sw tr na vl 100

interface Vlan88
 ip address 192.168.88.9 255.255.255.0
 no shutdown

ip default-gateway 192.168.88.6