enable
conf t

hostname KS1
vlan 10
 name HR
vlan 20
 name SALES
vlan 30
 name MARKETING
vlan 88
 name MANAGEMENT
vlan 100
 name SERVICES

interface vlan 88
 ip address 192.168.88.7 255.255.255.0
 no shutdown

ip default-gateway 192.168.88.1

interface fa0/1 
 switchport mode access
 switchport access vlan 10
 spanning-tree portfast

interface fa0/2
 switchport mode access
 switchport access vlan 20
 spanning-tree portfast

interface fa0/3
 switchport mode access
 switchport access vlan 30
 spanning-tree portfast
interface fa0/4-5
 switchport mode access
 switchport access vlan 100
 spanning-tree portfast

interface fa0/6-7
 description etherchannel
 switchport mode trunk
 channel-group 1 mode active 
 switchport trunk allowed vlan 10,20,30,88,100
interface port-channel 1  
sw mo tr 
interface g0/1
 description TO_KR1
 switchport mode trunk
 switchport trunk allowed vlan 10,20,30,88,100

interface g0/2
 description TO_KR2
 switchport mode trunk
 switchport trunk allowed vlan 10,20,30,88

spanning-tree mode rapid-pvst
spanning-tree portfast bpduguard default
do sh run