hostname UR1



interface GigabitEthernet0/1
 ip nat outside 

interface GigabitEthernet0/0.10
 ip nat inside
 encapsulation dot1Q 10

interface GigabitEthernet0/0.20
 encapsulation dot1Q 20
 ip nat inside
 
interface GigabitEthernet0/0.88
 encapsulation dot1Q 88
 ip nat inside

ip acc list 1 permit 192.168.1.0 0.0.0.255
ip nat inside source list 1 interface GigabitEthernet0/1 overload

router bgp 10 
 bgp router-id 4.4.4.4
 neighbor 9.11.69.73 remote-as 100
network 9.11.69.72
