hostname UR1



interface GigabitEthernet0/1
 crypto map MY_MAP
 ip nat outside 

interface GigabitEthernet0/0.10
 ip nat inside
 encapsulation dot1Q 10

interface GigabitEthernet0/0.20
 encapsulation dot1Q 20
 ip nat inside
 
interface GigabitEthernet0/0.88
 encapsulation dot1Q 88
 ip nat inside

ip acc list 1 permit 192.168.1.0 0.0.0.255
ip nat inside source list 1 interface GigabitEthernet0/1 overload

router bgp 10 
 bgp router-id 4.4.4.4
 neighbor 9.11.69.73 remote-as 100
network 9.11.69.72


  crypto isakmp policy 10
  encryption aes 256
  hash sha256
  authentication pre-share
  group 14
crypto isakmp key test address 9.11.69.66
crypto isakmp key test address 9.11.69.74

crypto ipsec transform-set MY_SET esp-aes 256 esp-sha256-hmac
ip access-list extended VPN_ACL
  permit ip 192.168.0.0 0.0.128.255 192.168.0.0 0.0.128.255
crypto map MY_MAP 10 ipsec-isakmp
  set peer 9.11.69.66
  set peer 9.11.69.74
  set transform-set MY_SET
  match address VPN_ACL