hostname US1

vlan 10
 name GUEST
vlan 20
 name DESKTOP
vlan 88 
 name MANAGEMENT
vlan 99
 name BLACKHOLE


no cdp run
no lldp run
spanning-tree mode rapid-pvst
spanning-tree portfast bpduguard default
spanning-tree portfast bpdufilter default

! Disable unused services
no service tcp-small-servers
no service udp-small-servers
no ip http server
no ip http secure-server


interface FastEthernet0/1
 description ACCESS_GUEST_VLAN10
 switchport mode access
 switchport access vlan 10
 switchport nonegotiate
 spanning-tree portfast
 spanning-tree bpduguard enable
 switchport port-security
 switchport port-security maximum 1
 switchport port-security mac-address sticky
 switchport port-security violation shutdown
 ip dhcp snooping limit rate 15
 ip arp inspection limit rate 100
 no cdp enable
 no lldp transmit
 no lldp receive
 no shutdown

interface GigabitEthernet0/1
 description ACCESS_DESKTOP_VLAN20
 switchport mode access
 switchport access vlan 20
 switchport nonegotiate
 spanning-tree portfast
 spanning-tree bpduguard enable
 switchport port-security
 switchport port-security maximum 2
 switchport port-security mac-address sticky
 switchport port-security violation shutdown
 ip dhcp snooping limit rate 15
 ip arp inspection limit rate 100
 no cdp enable
 no lldp transmit
 no lldp receive
 no shutdown

interface GigabitEthernet0/2
 description UPLINK_TRUNK
 switchport mode trunk
 switchport trunk allowed vlan 10,20,88
 switchport trunk native vlan 99
 switchport nonegotiate
 spanning-tree guard root
 no cdp enable
 no lldp transmit
 no lldp receive
 no shutdown

interface Vlan88
 description MANAGEMENT
 ip address 192.168.88.10 255.255.255.0
 no shutdown

interface range FastEthernet0/2 - 24
 description UNUSED_DISABLED
 switchport mode access
 switchport access vlan 99
 switchport nonegotiate
 spanning-tree portfast
 spanning-tree bpduguard enable
 no cdp enable
 no lldp transmit
 no lldp receive
 shutdown

ip dhcp snooping
ip dhcp snooping vlan 10,20,88
no ip dhcp snooping information option

ip arp inspection vlan 10,20,88

 interface FastEthernet0/1
  ip verify source
 interface GigabitEthernet0/1
  ip verify source

ip default-gateway 192.168.88.1

ip access-list standard MGMT_ACCESS
 permit 192.168.88.0 0.0.0.255
 deny   any log

line vty 0 15
 access-class MGMT_ACCESS in
 transport input ssh
 exec-timeout 5 0
 login local

line console 0
 exec-timeout 5 0
 login local