hostname IU1

vlan 10
 name GUEST
vlan 20
 name DESKTOP
vlan 99
 name BLACKHOLE

interface FastEthernet 0/1
 switchport mode access
 switchport access vlan 10

interface GigabitEthernet 0/1
switchport mode access
switchport access vlan 20

interface GigabitEthernet 0/2
 switchport mode trunk
 sw tr all vl 10,20
 sw tr na vl 99

interface Vlan88
 ip address 192.168.88.10 255.255.255.0
 no shutdown

ip default-gateway 192.168.88.1